### PR TITLE
Fix import for Crossref format 2022

### PR DESCRIPTION
**Pull request by lfoppiano**
This PR attempts to fix the import of the 2022 crossref file: 
 - [x] Import in LMDB (Java)
 - [ ] Import in Elastic (JS) 😭 
 - [ ] Test import 2021 Gz
 - [ ] Test import 2019

### CODE REVIEW

**Comment by karatekaneen** [comment]
@lfoppiano I can have a go at fixing the JS for you. My download is not finished yet, but can you describe what's the problem and I'll try to fix it?

**Comment by lfoppiano** [comment]
@karatekaneen basically supporting the 2022 format. Contrary to the 2021 is provided "pretty printed" so it cannot be parsed line by line as it was done before (see #78).

**Comment by karatekaneen** [comment]
Ok, I'll have a look when my download has finished and I find some time

**Comment by karatekaneen** [comment]
@lfoppiano I started looking at the javascript app but then quickly gave up 😆 .
Decided to rewrite it from scratch in Go to make it easier to read, more performant and easier to test.

I added tests to make sure both 2021 and 2022 dumps works as well as the incremental dumps being used. I don't have access to any of the Crossref premium files so could not add them but happy to do it if a sample can be provided.

There's also currently a problem (haven't opened an issue for it from what I can see) where the [relative path to the `indexing` folder differs](https://github.com/kermitt2/biblio-glutton/blob/master/lookup/src/main/java/com/scienceminer/lookup/utils/crossrefclient/IncrementalLoaderTask.java#L294-L295) if you are running it as a regular application or if you are running it in a docker container. By switching to a static binary we can get rid of all the Node dependencies as well as completely removing the issue with relative paths as long as we put the indexing app inside `$PATH`.

Have a look here (https://github.com/karatekaneen/crossrefindexer) if there's something more wanted, otherwise I'll try to switch out node in the next couple of days and test on our environment before opening a PR replacing it.

**Comment by lfoppiano** [comment]
Closing as this it's already integrated in #92

**Pull request closed without merging**
