### PR TITLE
Add Docker configuration

### PR DESCRIPTION
**Pull request by bfirsh**
This makes it much simpler to get a copy up and running.

I updated the default configuration files because I figure if you're running with it without Docker you're probably going to update those files anyway. Ideally those configuration options could be set with environment variables, which is much easier to do from Docker.

Another improvement could be some shell scripts to replace the rather long-winded data loading commands. `./load-crossref-data.sh data/crossref-works.2018-09-05.json.xz` or whatever. But I figure this is a good start. :)

### CODE REVIEW

**Comment by kermitt2** [comment]
Super, many thanks !

Loading PMID/PMC/DOI mapping and Unpaywall data dump will work the same way right? 

> $ docker-compose run biblio java -jar build/libs/lookup-service-1.0-SNAPSHOT-onejar.jar pmid --input PMID_PMCID_DOI.csv.gz data/config/config.yml 

> $ docker-compose run biblio java -jar build/libs/lookup-service-1.0-SNAPSHOT-onejar.jar unpaywall --input unpaywall_snapshot_2018-09-24T232615.jsonl.gz data/config/config.yml 

It looks too easy :) 

Of course the limit is that for scaling, a separate ElasticSearch cluster cannot be avoided. But for many simple usages, one node is likely enough.

**Comment by bfirsh** [comment]
Yes - more-or-less. Two non-obvious things:

- You need to prefix with `matching/` because the working directory is the root of the repo.
- You need to put the input in the `data/` directory because that is the only directory mounted inside the container

So, it'd be more like this: 

    $ docker-compose run biblio java -jar lookup/build/libs/lookup-service-1.0-SNAPSHOT-onejar.jar pmid --input data/PMID_PMCID_DOI.csv.g lookup/data/config/config.yml

I've documented the unpaywall one in the readme as an example.

The matching script is even more fiddly because it assumes the working directory is `matching/`, but it is possible to make it work.

Which is to say -- I think this is sufficiently fiddly that it needs some scripts! I'll sort in a follow-up PR if I get the time.

**Comment by lfoppiano** [comment]
FYI I'm on it... It's just taking longer than expected.

**Comment by lfoppiano** [comment]
@bfirsh I've pushed some changes in the dockerfile and the build. I've split the build and the run and I've used the distributed package to build the service (instead of using it from the sources). 
Could you please have a look at it and let me know if it's working? I did not manage to test it, cause somehow the port forwarding wasn't working in my docker.

**Comment by bfirsh** [comment]
Looks good to me!

**Comment by lfoppiano** [comment]
Thanks @bfirsh

**Pull request merged**
